<?php
defined('BASEPATH') OR exit('No direct script access allowed');
$route['default_controller'] = 'auth';
$route['404_override'] = '';
$route['translate_uri_dashes'] = FALSE;
$route['login'] = "Auth/cek_login";
$route['mahasiswa'] = "mahasiswa/dashboard";
$route['logout'] = "auth/logout";
$route['administrator/(:any)']  = 'admin/$1';
$route['administrator/mahasiswa/(:any)'] = "admin/mahasiswa/$1";
$route['administrator/dosen/(:any)'] = "admin/dosen/$1";
$route['administrator/entry_khs/(:any)'] = "admin/entry_khs/$1";
$route['administrator/jurusan/(:any)'] = "admin/jurusan/$1";
$route['administrator/khs/(:any)'] = "admin/khs/$1";
$route['administrator/kurikulum/(:any)'] = "admin/kurikulum/$1";
$route['administrator/matakuliah/(:any)'] = "admin/matakuliah/$1";
$route['administrator/mksyarat/(:any)'] = "admin/mksyarat/$1";
$route['administrator/nilai/(:any)'] = "admin/nilai/$1";
$route['administrator/qmatakuliah/(:any)'] = "admin/qmatakuliah/$1";
$route['administrator/qnilai/(:any)'] = "admin/qnilai/$1";
$route['administrator/semester/(:any)'] = "admin/semester/$1";
$route['administrator/semester_sekarang/(:any)'] = "admin/semester_sekarang/$1";
$route['administrator/tahun_ajaran/(:any)'] = "admin/tahun_ajaran/$1";
$route['administrator/ukmppd/(:any)'] = "admin/ukmppd/$1";
$route['administrator/user/(:any)'] = "admin/user/$1";
$route['administrator/group/(:any)'] = "auth/create_group/$1";